# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-05 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='product',
            name='item_brand',
            field=models.CharField(choices=[('addidas', ('Addidas', 'images/brand/addidas.jpeg')), ('under-armour', ('Under Armour', 'images/brand/under-armour.jpeg'))], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='item_categories',
            field=models.CharField(choices=[('balls', ('Balls', 'images/brand/balls.jpeg')), ('rackets', ('Rackets', 'images/brand/rackets.jpeg')), ('apparel', ('Apparel', 'images/brand/apparel.jpeg'))], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='images/profiles/default.jpg', upload_to='images/profiles/'),
        ),
    ]
