# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20200305_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_brand',
            field=models.CharField(choices=[('Addidas', 'images/brand/addidas.jpeg'), ('Under Armour', 'images/brand/under-armour.jpeg')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_categories',
            field=models.CharField(choices=[('Balls', 'images/brand/balls.jpeg'), ('Rackets', 'images/brand/rackets.jpeg'), ('Apparel', 'images/brand/apparel.jpeg')], max_length=1, null=True),
        ),
    ]
