# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20200305_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_image', models.ImageField(upload_to='images/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='item_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_description',
            field=models.CharField(max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_details',
            field=models.CharField(max_length=1000, verbose_name='Item Details'),
        ),
    ]
