# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-05 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_auto_20200305_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
