# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-03 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0005_auto_20200209_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/product/')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=50)),
                ('item_details', models.CharField(max_length=500)),
                ('item_availability', models.BooleanField(default=False)),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_image', models.ImageField(upload_to='images/brand/')),
            ],
            options={
                'ordering': ['images'],
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
