# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-05 04:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/product/')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.CharField(max_length=50)),
                ('item_details', models.CharField(max_length=500)),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_availability', models.BooleanField(default=False)),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_image', models.ImageField(upload_to='images/brand/')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='default.jpg', upload_to='images/profiles/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
