# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200305_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_description',
            field=models.TextField(max_length=200, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_details',
            field=models.TextField(max_length=1000, verbose_name='Item Details'),
        ),
    ]
