# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200307_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_item_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_item_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
