# Generated by Django 2.2.13 on 2020-12-03 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=20)),
                ('brand_image', models.ImageField(upload_to='images/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/product/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(default='images/profiles/default.jpg', upload_to='images/profiles/')),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('item_description', models.TextField(max_length=200, verbose_name='Item Description')),
                ('item_price', models.FloatField(default=0.0)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('item_details', models.TextField(max_length=1000, verbose_name='Item Details')),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_availability', models.BooleanField(default=False)),
                ('is_item_featured', models.BooleanField(default=False)),
                ('is_item_recommended', models.BooleanField(default=False)),
                ('item_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand')),
                ('item_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
                ('item_images', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Images')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
