# Generated by Django 2.2.13 on 2020-12-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_images',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/product/image-placeholder-500x500.jpg', upload_to='images/product/'),
        ),
    ]
