# Generated by Django 2.2.13 on 2020-12-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201203_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
