# Generated by Django 2.2.13 on 2020-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_delete_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='item_image',
        ),
    ]
