# Generated by Django 2.2.13 on 2020-12-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201204_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(default='Enter Description', max_length=200),
        ),
    ]
