# Generated by Django 2.2.13 on 2020-12-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(default='images/product/zohari_image_placeholder.png', upload_to='images/product/'),
        ),
    ]
